insert into ape(version, id, color) values (1, 1, 'apricot')
insert into ape(version, id, color) values (1, 2, 'apple')
insert into car(version, id, color) values (1, 1, 'cocoa')
insert into car(version, id, color) values (1, 2, 'cream')
insert into sample_person(version, id, ape, d, e) values (1, 1, 1, 'd', 'e')
insert into sample_person(version, id, ape, d, e) values (1, 2, 2, 'd', 'e')
insert into sample_person_assoc_car(version, id, sample_person, car) values (1,1,1,1)
insert into sample_person_assoc_car(version, id, sample_person, car) values (1,2,1,2)
insert into sample_person_assoc_car(version, id, sample_person, car) values (1,3,2,2)
insert into bat(version, id, color, zookeeper) values (1, 1, 'brown', 1)
insert into bat(version, id, color, zookeeper) values (1, 2, 'blue', 1)
insert into bat(version, id, color, zookeeper) values (1, 2, 'burgundy', 2)

